import { Router } from 'express';
import archiver from 'archiver';
import { PassThrough } from 'stream';

const router = Router();

const exports = new Map();

// Code generation templates
const templates = {
  'frontend/layout.tsx': `import type { Metadata } from 'next';
export const metadata: Metadata = { title: '{{projectName}}', description: 'Generated by Leo AI' };
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <html lang="en"><body>{children}</body></html>;
}`,
  'frontend/page.tsx': `export default function HomePage() {
  return <main><h1>{{projectName}}</h1><p>Generated by Leo AI Platform</p></main>;
}`,
  'backend/index.ts': `import express from 'express';
const app = express();
app.use(express.json());
app.get('/health', (_req, res) => res.json({ status: 'ok' }));
app.listen(3001, () => console.log('Backend running'));
`,
  'firebase/firestore.rules': `rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth != null;
    }
  }
}`,
  'docker-compose.yml': `version: '3.8'
services:
  frontend:
    build: ./frontend
    ports: ["3000:3000"]
  backend:
    build: ./backend
    ports: ["3001:3001"]
    environment:
      - NODE_ENV=production
  redis:
    image: redis:7-alpine`,
  'README.md': `# {{projectName}}

Generated by Leo AI Platform.

## Setup

1. Run \`npm install\`
2. Configure \`.env\` from \`.env.example\`
3. Run \`docker-compose up\`
`,
};

router.post('/generate', (req, res) => {
  const exportId = `export_${Date.now()}`;
  const { projectId, includeBackend, includeDocker, format } = req.body;

  const exportJob = {
    id: exportId,
    projectId,
    status: 'processing',
    progress: 0,
    estimatedTime: 30,
    createdAt: new Date().toISOString(),
  };

  exports.set(exportId, exportJob);

  // Simulate generation
  setTimeout(() => {
    exportJob.status = 'completed';
    exportJob.progress = 100;
    exportJob.completedAt = new Date().toISOString();
  }, 2000);

  res.json({ success: true, data: { exportId, status: 'processing', estimatedTime: 30 } });
});

router.get('/:exportId/status', (req, res) => {
  const exportJob = exports.get(req.params.exportId);
  if (!exportJob) return res.status(404).json({ success: false, error: 'Export not found' });
  res.json({ success: true, data: exportJob });
});

router.get('/:exportId/download', (req, res) => {
  const exportJob = exports.get(req.params.exportId);
  if (!exportJob) return res.status(404).json({ success: false, error: 'Export not found' });

  const projectName = exportJob.projectId || 'leo-ai-project';

  res.setHeader('Content-Type', 'application/zip');
  res.setHeader('Content-Disposition', `attachment; filename="${projectName}.zip"`);

  const archive = archiver('zip', { zlib: { level: 9 } });
  archive.pipe(res);

  // Add template files
  Object.entries(templates).forEach(([path, content]) => {
    archive.append(content.replace(/{{projectName}}/g, projectName), { name: path });
  });

  // Add workflow JSON if available
  archive.append(JSON.stringify({ name: projectName, exportedAt: new Date().toISOString() }, null, 2), { name: 'workflow.json' });

  archive.append(`FIREBASE_API_KEY=
FIREBASE_PROJECT_ID=
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
`, { name: '.env.example' });

  archive.finalize();
});

export default router;
